name: Central Notify

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      enabled:
        required: false
        type: boolean
    secrets:
      TEAMS_WEBHOOKS_JSON:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ inputs.enabled != false }}
    steps:
      - name: Parse channels and send notifications
        run: |
          echo "Message: ${{ inputs.message }}"

          echo '${{ secrets.TEAMS_WEBHOOKS_JSON }}' | jq -R 'fromjson | to_entries[] | "\(.key) \(.value)"' | while read key url; do
            echo "Sending to $key: $url"
            curl -H "Content-Type: application/json" \
                 -d "{\"text\": \"${{ inputs.message }}\"}" \
                 "$url"
          done

## Add secrets:
# Secret name: TEAMS_WEBHOOKS_JSON
# Value: 
# {
#   "DEV": "https://outlook.office.com/webhook/xxx",
#   "QA": "https://outlook.office.com/webhook/yyy",
#   "TEST": "https://outlook.office.com/webhook/zzz"
# }


# name: Central Notify

# on:
#   workflow_call:
#     inputs:
#       message:
#         required: true
#         type: string
#       enabled:
#         required: false
#         type: boolean
#     secrets:
#       TEAMS_WEBHOOK_URL:
#         required: true

# jobs:
#   notify:
#     runs-on: ubuntu-latest
#     if: ${{ inputs.enabled != false }}
#     steps:
#       - name: Send Teams notification
#         run: |
#           echo "Sending message: ${{ inputs.message }}"
#           curl -H "Content-Type: application/json" \
#                -d "{\"text\": \"${{ inputs.message }}\"}" \
#                "${{ secrets.TEAMS_WEBHOOK_URL }}"
