##### Notifications with filter demo
# name: Central Notify

# on:
#   workflow_call:
#     inputs:
#       message:
#         required: true
#         type: string
#       enabled:
#         required: false
#         type: boolean
#     secrets:
#       TEAMS_WEBHOOKS_JSON:
#         required: true

# jobs:
#   notify:
#     runs-on: ubuntu-latest
#     if: ${{ inputs.enabled != false }}
#     steps:
#       - name: Skip demo releases
#         if: ${{ contains(inputs.message, 'demo') }}
#         run: |
#           echo "Skipping notification for demo release: ${{ inputs.message }}"

#       - name: Parse channels and send notifications
#         if: ${{ !contains(inputs.message, 'demo') }}
#         run: |
#           echo "Message: ${{ inputs.message }}"

#           echo '${{ secrets.TEAMS_WEBHOOKS_JSON }}' \
#           | jq -r 'to_entries[] | "\(.key) \(.value)"' \
#           | while read key url; do
#               echo "Sending to $key: $url"
#               curl -H "Content-Type: application/json" \
#                    -d "{\"text\": \"${{ inputs.message }}\"}" \
#                    "$url"
#             done
########################################################
##### Notifications for differents teams################

# name: Central Notify

# on:
#   workflow_call:
#     inputs:
#       message:
#         required: true
#         type: string
#       enabled:
#         required: false
#         type: boolean
#     secrets:
#       TEAMS_WEBHOOKS_JSON:
#         required: true

# jobs:
#   notify:
#     runs-on: ubuntu-latest
#     if: ${{ inputs.enabled != false }}
#     steps:
#       - name: Parse channels and send notifications
#         run: |
#           echo "Message: ${{ inputs.message }}"

#           echo '${{ secrets.TEAMS_WEBHOOKS_JSON }}' \
#           | jq -r 'to_entries[] | "\(.key) \(.value)"' \
#           | while read key url; do
#               echo "Sending to $key: $url"
#               curl -H "Content-Type: application/json" \
#                    -d "{\"text\": \"${{ inputs.message }}\"}" \
#                    "$url"
#             done

###Add secrets:
# Secret name: TEAMS_WEBHOOKS_JSON
# Value: 
# {"DEV":"https://outlook.office.com/webhook/xxx","QA": "https://outlook.office.com/webhook/yyy",}
############ in JSON format without spaces and with regular quotes ####

########################################################
######## Using webhooks for each repo ##########
name: Central Notify

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      enabled:
        required: false
        type: boolean
    secrets:
      TEAMS_DEV_WEBHOOK:
        required: true
      TEAMS_QA_WEBHOOK:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ inputs.enabled != false }}
    steps:
      - name: Send Teams notification to Dev team (skip qa-tagged)
        if: ${{ !contains(inputs.message, 'qa') }}
        run: |
          echo "Sending to Dev channel: ${{ inputs.message }}"
          curl -H "Content-Type: application/json" \
               -d "{\"text\": \"[Dev Notification] ${{ inputs.message }}\"}" \
               "${{ secrets.TEAMS_DEV_WEBHOOK }}"

      - name: Send Teams notification to QA team (skip release-tagged)
        if: ${{ !contains(inputs.message, 'release') }}
        run: |
          echo "Sending to QA channel: ${{ inputs.message }}"
          curl -H "Content-Type: application/json" \
               -d "{\"text\": \"[QA Notification] ${{ inputs.message }}\"}" \
               "${{ secrets.TEAMS_QA_WEBHOOK }}"
