name: Central Notify

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      enabled:
        required: false
        type: boolean
    secrets:
      TEAMS_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ inputs.enabled != false }}
    steps:
      - name: Send Teams notification
        run: |
          echo "Sending message: ${{ inputs.message }}"
          curl -H "Content-Type: application/json" \
               -d "{\"text\": \"${{ inputs.message }}\"}" \
               "${{ secrets.TEAMS_WEBHOOK_URL }}"